"""empty message

Revision ID: 0a0e9de30167
Revises: bdcd22147a13
Create Date: 2025-01-12 14:31:57.899330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0e9de30167'
down_revision = 'bdcd22147a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respond', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('date_of_respond', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support', schema=None) as batch_op:
        batch_op.drop_column('date_of_respond')
        batch_op.drop_column('respond')

    # ### end Alembic commands ###
